### ISSUE TITLE
Installed spyder-notebook but notebook tab not showing

### ISSUE THREAD

**Issue by dmrobotix** [spyder-ide/spyder-notebook#146]
## Description of your problem

I don't see the editor and notebook tabs when I launch spyder. 
Not sure what I'm doing wrong. Thanks!

**What steps will reproduce the problem?**

1. In terminal run command: conda install spyder-notebook -c spyder-ide
2. Open spyder3 from Anaconda Navigator

**What is the expected output? What do you see instead?**
I expect to see the notebook tab and editor tab at the bottom of the program but I don't see either.

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

<img width="1280" alt="screen shot 2018-03-22 at 10 24 24" src="https://user-images.githubusercontent.com/10948188/37776291-505a5cd0-2dbb-11e8-9088-c3f32e528acd.png">

## Versions and main components

* Spyder Version: 3.2.8
* Python Version: 3.6.3
* Qt Version: 7.7.3
* PyQt Version: 5.6.0
* Jupyter Notebook Version: 5.4.0
* Operating system: Mac OS X 10.13.3

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Could you open Spyder from the terminal and try again?

**Comment by camililla** [comment]
I have the same problem. I open Spyder from the terminal and get this

`[I 10:26:20.805 NotebookApp] JupyterLab beta preview extension loaded from /home/alfonso/anaconda2/envs/py36/lib/python3.6/site-packages/jupyterlab
[I 10:26:20.805 NotebookApp] JupyterLab application directory is /home/alfonso/anaconda2/envs/py36/share/jupyter/lab
[I 10:26:20.809 NotebookApp] Serving notebooks from local directory: /tmp/spyder-alfonso/notebooks
[I 10:26:20.809 NotebookApp] 0 active kernels
[I 10:26:20.809 NotebookApp] The Jupyter Notebook is running at:
[I 10:26:20.809 NotebookApp] http://localhost:8888/?token=bf975b4312d7b5aa7e1228142921f2768f6a2c78b8d453a1
[I 10:26:20.809 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:26:20.809 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=bf975b4312d7b5aa7e1228142921f2768f6a2c78b8d453a1
[W 10:26:21.457 NotebookApp] Notebook untitled0.ipynb is not trusted
[W 10:26:21.533 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180411102620 (127.0.0.1) 5.27ms referer=http://localhost:8888/notebooks/untitled0.ipynb
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
[I 10:26:21.605 NotebookApp] Kernel started: 1f930cb9-9513-45d4-9b81-0614f6d6122e
[I 10:26:22.548 NotebookApp] Adapting to protocol v5.1 for kernel 1f930cb9-9513-45d4-9b81-0614f6d6122e
[I 10:28:21.564 NotebookApp] Saving file at /untitled0.ipynb
`
I'm not sure if I should run something before hand or if there's a problem with the package.

**Comment by danieltomasz** [comment]
In some cases when changing in Spyder View > Windows  Layout to different view,  notebook addon is unticked in Panes (so it dissaper from Spyder Windows)
When ticked again it land in land in the same windows as variable explorer (upper right window in spyder layout) not in the editor window (I am not treating this as bug but it may be confusing for some users, so I am writing it down here)

**Comment by jitseniesen** [comment]
Not sure if there is an issue here. For future reference, if you do not see the notebook tab then try selecting `View` > `Panes` > `Notebooks`.

**Comment by maderafunk** [comment]
The notebook doesn't show up for me either, using Spyder 3.3.2. There is also no option under View > Panes. When I open a python notebook, it is only shown in editor mode. There is an option to convert it to a python script however, I am not sure, if that was part of the standard spyder version.

**Comment by ccordoba12** [comment]
There's a little incompatibility with 3.3.2 that will be fixed in the next release of this plugin.

**Comment by Okroshiashvili** [comment]
I installed spyder-Notebook plugin. It worked properly but after updating conda Jupyter notebook tab disappeared from spyder and it also disappeared from `View` > `Panes`. What should I do? I reinstalled the plugin using both conda and pip but still do not see the Notebook tab

**Comment by ccordoba12** [comment]
@Okroshiashvili, please see my message above.

**Comment by mmagnuski** [comment]
I've had this problem lately helping a collegue to install spyder-notebook, we've tested many approaches and only installing from spyder-notebook from conda-forge (and not pip) worked in the end (we did not want to install from conda-forge at the beginning because that forced a downgrade of python from 3.7 to 3.6). At the beginning the notebook pane would be completely empty, than after another try it disappeared (also from view -> panes menu) but installing from conda-forge helped.

**Comment by jitseniesen** [comment]
> There's a little incompatibility with 3.3.2 that will be fixed in the next release of this plugin.

To be more explicit, spyder-notebook does not work with Spyder 3.3.2, so if you have upgraded Spyder then the notebook plugin will no longer work.

I am trying to do a release this week to fix this, but due to the holidays I'm not sure when it will appear.

**Comment by jiecui** [comment]
At the time of this writing, if you downgrade Spyder from 3.3.2 to 3.3.1, the notebook tab appears (python=2.7, MacOs).

**Comment by jiecui** [comment]
p.s.: It also works, if you upgrade Spyder from 3.3.2 to 4.0.0b1 (python=2.7, MacOs).

**Comment by mmagnuski** [comment]
> I am trying to do a release this week to fix this, but due to the holidays I'm not sure when it will appear.

Thanks for the info, I've seen a PR to fix it some time ago here and I assumed that the new release was already available through pip, my fault, sorry for the noise. :)

**Comment by jitseniesen** [comment]
The new release should be available now, though it has not been announced yet. You are looking for spyder-notebook version 0.1.4.

**Comment by Okroshiashvili** [comment]
@jitseniesen will this solve spyder 3.3.2 incompatibility problem?

**Comment by biorad** [comment]
I just installed the latest versions of Python, Spyder, and Spyder Notebook, but I am having the same problem as the original poster - No Notebook option is shown under Panes.  

Spyder Version: 4.1.4
Python Version: 3.8
Jupyter Notebook Version: 6.0.3
Operating system: Mac OS Catalina 10.15.7

**Comment by BrazilForever11** [comment]
Same here, no notebook option anywhere

Spyder 4.1.5
Python 3.7.9
OS: Windows 10

**Comment by mmagnuski** [comment]
I have a student on my classes who experiences the same problem on Mac.

**Comment by jitseniesen** [comment]
@BrazilForever11 @mmagnuski I don't know, perhaps there is a dependency issue somewhere which prevents the notebook plugin from being initialized properly. This is how I would start debugging this.
1. In Spyder, check whether `spyder-notebook` appears in the list produced by `Help > Dependencies`. If yes, the plugin is initialized but does not work for some reason; go to the last step. If no, the plugin is not initialized; continue with the next step.
2. Check whether `spyder-notebook` is installed in the environment that you run Spyder from. If no, then that is the problem.
3. Open a Python prompt and execute `import spyder_notebook`. This will probably show an error indicating the issue.
4. As a last resort, run Spyder with debugging enabled (command: `spyder --debug-info verbose`) and look for errors in the debug output.

**Comment by mmagnuski** [comment]
@jitseniesen Turned out the problem with spyder-notebook was present only when running Spyder from the Anaconda Launcher, but the notebook worked ok when starting Spyder from the terminal.

**Comment by saprativa** [comment]
On Spyder 5.0.5

```import spyder_notebook``` gives the following error:

```
 File "/var/folders/wx/m13c2nmx72n4d9ng8bz_kn340000gn/T/ipykernel_870/1627363730.py", line 1, in <module>
    import spyder_notebook

  File "/Users/saprativa/opt/anaconda3/lib/python3.8/site-packages/spyder_notebook/__init__.py", line 11, in <module>
    from spyder_notebook.notebookplugin import NotebookPlugin as PLUGIN_CLASS

  File "/Users/saprativa/opt/anaconda3/lib/python3.8/site-packages/spyder_notebook/notebookplugin.py", line 26, in <module>
    from spyder.config.main import CONF

ImportError: cannot import name 'CONF' from 'spyder.config.main' (/Users/saprativa/opt/anaconda3/lib/python3.8/site-packages/spyder/config/main.py)
```

**Comment by ccordoba12** [comment]
Spyder-notebook is not compatible with Spyder 5 yet.

**Comment by habtie-phy** [comment]
> Spyder-notebook is not compatible with Spyder 5 yet.

how soon would it be compatible?

**Comment by Micha12323** [comment]
Well at the Spyder 5 Documentation there is an [entry ](https://docs.spyder-ide.org/5/plugins/notebook.html)how to install the notebook-extention. But its with spyder 4 images :D 

That was my faulty way up to here :D Thanks for your help!

**Comment by mg3146** [comment]
Hi - is Spyder-notebook compatible with Spyder 5.3.3?    I just ran the conda install line from the [Spyder website](https://docs.spyder-ide.org/5/plugins/notebook.html#:~:text=Spyder%2Dnotebook%20is%20a%20plugin,Variable%20explorer%2C%20console%20and%20debugger.) but there is no notebook option in the Panels dropdown.

**Comment by luukalt** [comment]
@mg3146 I encounter the same problem!

**Comment by alemdar69** [comment]
I have the same problem, I was on 5.3.3 and had the notebook and terminal running ok, but when I upgraded to 5.4.1 they both disappeared, and in fact Terminal started causing crash to Spyder (fails to start), after removing both, and downgrading Spyder to 5.3.3, I reinstalled the notebook, but it does not show in the panes view at all, I tried all the option above, like changing the layout, start Sypder using the navigator, but nothing works, I cannot see the notebook in the panes view, and installing the terminal causes Spyder to crash (I am talking about Spyder 5.3.3, enen though they both worked before the upgrade/downgrade)
However, if I go to the Anaconda navigator, I can see the notebook under the root environment, but does not show under panes.

**Comment by Micha12323** [comment]
Back in my times, there was no integration for spyder 5.xx. So I think it's an other issue..

**Comment by alemdar69** [comment]
It seems that you are talking about 20 or 30 years ago 😃
Definitely there is an issue somewhere, because for example, I couldn't install the NB through conda prompt, either it fails or install V0.1.4, I had to download the source files and do manual installation, but still cannot see it in the panes section, and even the Navigator still recognise it as the old version

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by poojaparameswaran99** [comment]
I am on Spyder 5.4.3 and I ran `conda install spyder-notebook -c conda-forge` but I am not seeing the Notebook option under View -> Panes. Should I run another command to get this option/view? Thank you I appreciate all help.

**Comment by danieltomasz** [comment]
@poojaparameswaran99  are you sure you installed spyder notebook to same  virtual environment as you installed spyder?
